// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpxbqmmhwplpxklsmkrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRweGJxbW1od3BscHhrbHNta3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTc0MzYsImV4cCI6MjA2MTk3MzQzNn0.Xy8tgqPPaFazZVPgtR9CTi-_6g9zJ82Z8GmgFK64mAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);